#!/bin/bash
# Ver: 1.1 by Endial Fang (endial@126.com)
#
# shell 执行参数，分别为 -e(命令执行错误则退出脚本) -u(变量未定义则报错) -x(打印实际待执行的命令行)
set -eux

APP_DIRS=" \
	/usr/local/${APP_NAME} \
	/etc/${APP_NAME} \
	/srv/conf/${APP_NAME} \
	/srv/data/${APP_NAME} \
	/srv/datalog/${APP_NAME} \
	/var/cache/${APP_NAME} \
	/var/run/${APP_NAME} \
	/var/log/${APP_NAME} \
	/srv/cert/${APP_NAME}"

mkdir -p ${APP_DIRS}
chown -Rf ${APP_USER}:${APP_USER} ${APP_DIRS}; 
